### ISSUE TITLE
Fix BicycleObject hierarchy

### ISSUE THREAD

**Issue by mickvangelderen** [oliverlee/bikesim#15]
The BicycleObject GameObject does not leverage the transformation hierarchy Unity provides. Rendering the Bicycle from the x, y and a couple of angles is rather simple, provided that the GameObject is built hierarchically.

![image](https://cloud.githubusercontent.com/assets/5444990/24906033/78691ee2-1eb6-11e7-9ba5-9a8a1b7792d8.png)

The wheels should be children of their respective frames. The front frame should be a child of the back frame.

Applying this principle will simplify the code in `BicycleController.SetBicycleTransform` tremendously.

Also, the front wheel is bigger (scale .7) than the back wheel (scale .6). Not sure if intentional.

**Comment by oliverlee** [comment]
> Also, the front wheel is bigger (scale .7) than the back wheel (scale .6). Not sure if intentional.

While a bit weird, this is intentional. Geometry of the bicycle is taken from the benchmark parameters as described here: http://rspa.royalsocietypublishing.org/content/463/2084/1955#T1

**Comment by mickvangelderen** [comment]
Seems there is no need for this after all because we have some code that sets the transforms correctly. It is not easy to change though. Doing the work for this issue is not worth it anymore, unless the model will look much better afterwards.
