### ISSUE TITLE
Compare state evolution of simulation and experimental setup

### ISSUE THREAD

**Issue by oliverlee** [oliverlee/bikesim#6]
As we have not calculated the inertia of the handlebar of the stationary bicycle setup, which we know differs from the mass/inertia benchmark properties which are used in the simulation, the response of the physical system will differ from the response predicted by the simulation. Compare the state trajectory of the physical system to a simulation given the same torque input and same initial condition, and determine if a better actuator torque can be applied resulting in higher setup fidelity.

**Comment by magrotto** [comment]
Another idea could be to identify the inertia of the simulator handlebar by implementing a torsional spring with a proportional control. When a perturbation is given to the handlebar the control will try to bring the handlebar back to the original position. The inertia can be identify by studying the decay of the handlebar angle.

**Comment by oliverlee** [comment]
This has been implemented in https://github.com/oliverlee/phobos
